# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scara_command/CheckKinIKRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CheckKinIKRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "scara_command/CheckKinIKRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CheckKinIKRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scara_command/CheckKinIKResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CheckKinIKResponse(genpy.Message):
  _md5sum = "36714075758334348b25a38f8ec94251"
  _type = "scara_command/CheckKinIKResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 state_q1
float32 state_q2
float32 state_q3
float32 ik_q1
float32 ik_q2
float32 ik_q3
bool correct

"""
  __slots__ = ['state_q1','state_q2','state_q3','ik_q1','ik_q2','ik_q3','correct']
  _slot_types = ['float32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state_q1,state_q2,state_q3,ik_q1,ik_q2,ik_q3,correct

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CheckKinIKResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.state_q1 is None:
        self.state_q1 = 0.
      if self.state_q2 is None:
        self.state_q2 = 0.
      if self.state_q3 is None:
        self.state_q3 = 0.
      if self.ik_q1 is None:
        self.ik_q1 = 0.
      if self.ik_q2 is None:
        self.ik_q2 = 0.
      if self.ik_q3 is None:
        self.ik_q3 = 0.
      if self.correct is None:
        self.correct = False
    else:
      self.state_q1 = 0.
      self.state_q2 = 0.
      self.state_q3 = 0.
      self.ik_q1 = 0.
      self.ik_q2 = 0.
      self.ik_q3 = 0.
      self.correct = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6fB().pack(_x.state_q1, _x.state_q2, _x.state_q3, _x.ik_q1, _x.ik_q2, _x.ik_q3, _x.correct))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.state_q1, _x.state_q2, _x.state_q3, _x.ik_q1, _x.ik_q2, _x.ik_q3, _x.correct,) = _get_struct_6fB().unpack(str[start:end])
      self.correct = bool(self.correct)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6fB().pack(_x.state_q1, _x.state_q2, _x.state_q3, _x.ik_q1, _x.ik_q2, _x.ik_q3, _x.correct))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.state_q1, _x.state_q2, _x.state_q3, _x.ik_q1, _x.ik_q2, _x.ik_q3, _x.correct,) = _get_struct_6fB().unpack(str[start:end])
      self.correct = bool(self.correct)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6fB = None
def _get_struct_6fB():
    global _struct_6fB
    if _struct_6fB is None:
        _struct_6fB = struct.Struct("<6fB")
    return _struct_6fB
class CheckKinIK(object):
  _type          = 'scara_command/CheckKinIK'
  _md5sum = '36714075758334348b25a38f8ec94251'
  _request_class  = CheckKinIKRequest
  _response_class = CheckKinIKResponse
