panda:                    #useful if you use a namespace for the robot
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
        
    joint1_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint1
        pid: {p: 12000.0, i: 0.00, d: 50}

    joint2_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint2
        pid: {p: 12000.0, i: 0.00, d: 50}
        
    joint3_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint3
        pid: {p: 12000.0, i: 0.00, d: 50}

    joint4_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint4
        pid: {p: 12000.0, i: 0.00, d: 50}
    
    joint5_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint5
        pid: {p: 12000.0, i: 0.00, d: 50}

    joint6_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint6
        pid: {p: 12000.0, i: 0.00, d: 50}
        
    joint7_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint7
        pid: {p: 12000.0, i: 0.00, d: 50}            
    
    panda_finger1_controller:
        type: effort_controllers/JointPositionController
        joint: panda_finger_joint1
        pid: { p: 100000, d: 10.0, i: 0, i_clamp: 1 }            
    panda_finger2_controller:
        type: effort_controllers/JointPositionController
        joint: panda_finger_joint2
        pid: { p: 100000, d: 20.0, i: 0, i_clamp: 1 }

    joint1_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint1
        pid: {p: 6000.0, i: 0.00, d: 50}

    joint2_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint2
        pid: {p: 6000.0, i: 0.00, d: 50}
        
    joint3_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint3
        pid: {p: 6000.0, i: 0.00, d: 50}

    joint4_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint4
        pid: {p: 6000.0, i: 0.00, d: 50}
    
    joint5_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint5
        pid: {p: 6000.0, i: 0.00, d: 50}

    joint6_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint6
        pid: {p: 6000.0, i: 0.00, d: 50}
        
    joint7_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint7
        pid: {p: 6000.0, i: 0.00, d: 50}            
