// Generated by gencpp from file scara_command/CheckKinIKRequest.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_CHECKKINIKREQUEST_H
#define SCARA_COMMAND_MESSAGE_CHECKKINIKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct CheckKinIKRequest_
{
  typedef CheckKinIKRequest_<ContainerAllocator> Type;

  CheckKinIKRequest_()
    {
    }
  CheckKinIKRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::scara_command::CheckKinIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::CheckKinIKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckKinIKRequest_

typedef ::scara_command::CheckKinIKRequest_<std::allocator<void> > CheckKinIKRequest;

typedef boost::shared_ptr< ::scara_command::CheckKinIKRequest > CheckKinIKRequestPtr;
typedef boost::shared_ptr< ::scara_command::CheckKinIKRequest const> CheckKinIKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::CheckKinIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::CheckKinIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::CheckKinIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::CheckKinIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::scara_command::CheckKinIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/CheckKinIKRequest";
  }

  static const char* value(const ::scara_command::CheckKinIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::scara_command::CheckKinIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckKinIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::CheckKinIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::scara_command::CheckKinIKRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_CHECKKINIKREQUEST_H
