// Generated by gencpp from file scara_command/CheckKinFK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_CHECKKINFK_H
#define SCARA_COMMAND_MESSAGE_CHECKKINFK_H

#include <ros/service_traits.h>


#include <scara_command/CheckKinFKRequest.h>
#include <scara_command/CheckKinFKResponse.h>


namespace scara_command
{

struct CheckKinFK
{

typedef CheckKinFKRequest Request;
typedef CheckKinFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckKinFK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::CheckKinFK > {
  static const char* value()
  {
    return "6dd4bd6e62545926c2a7502c0ee7c4f1";
  }

  static const char* value(const ::scara_command::CheckKinFK&) { return value(); }
};

template<>
struct DataType< ::scara_command::CheckKinFK > {
  static const char* value()
  {
    return "scara_command/CheckKinFK";
  }

  static const char* value(const ::scara_command::CheckKinFK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::CheckKinFKRequest> should match
// service_traits::MD5Sum< ::scara_command::CheckKinFK >
template<>
struct MD5Sum< ::scara_command::CheckKinFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::CheckKinFK >::value();
  }
  static const char* value(const ::scara_command::CheckKinFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::CheckKinFKRequest> should match
// service_traits::DataType< ::scara_command::CheckKinFK >
template<>
struct DataType< ::scara_command::CheckKinFKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::CheckKinFK >::value();
  }
  static const char* value(const ::scara_command::CheckKinFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::CheckKinFKResponse> should match
// service_traits::MD5Sum< ::scara_command::CheckKinFK >
template<>
struct MD5Sum< ::scara_command::CheckKinFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::CheckKinFK >::value();
  }
  static const char* value(const ::scara_command::CheckKinFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::CheckKinFKResponse> should match
// service_traits::DataType< ::scara_command::CheckKinFK >
template<>
struct DataType< ::scara_command::CheckKinFKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::CheckKinFK >::value();
  }
  static const char* value(const ::scara_command::CheckKinFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_CHECKKINFK_H
