// Generated by gencpp from file scara_command/CheckKinIK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_CHECKKINIK_H
#define SCARA_COMMAND_MESSAGE_CHECKKINIK_H

#include <ros/service_traits.h>


#include <scara_command/CheckKinIKRequest.h>
#include <scara_command/CheckKinIKResponse.h>


namespace scara_command
{

struct CheckKinIK
{

typedef CheckKinIKRequest Request;
typedef CheckKinIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckKinIK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::CheckKinIK > {
  static const char* value()
  {
    return "36714075758334348b25a38f8ec94251";
  }

  static const char* value(const ::scara_command::CheckKinIK&) { return value(); }
};

template<>
struct DataType< ::scara_command::CheckKinIK > {
  static const char* value()
  {
    return "scara_command/CheckKinIK";
  }

  static const char* value(const ::scara_command::CheckKinIK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::CheckKinIKRequest> should match
// service_traits::MD5Sum< ::scara_command::CheckKinIK >
template<>
struct MD5Sum< ::scara_command::CheckKinIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::CheckKinIK >::value();
  }
  static const char* value(const ::scara_command::CheckKinIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::CheckKinIKRequest> should match
// service_traits::DataType< ::scara_command::CheckKinIK >
template<>
struct DataType< ::scara_command::CheckKinIKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::CheckKinIK >::value();
  }
  static const char* value(const ::scara_command::CheckKinIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::CheckKinIKResponse> should match
// service_traits::MD5Sum< ::scara_command::CheckKinIK >
template<>
struct MD5Sum< ::scara_command::CheckKinIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::CheckKinIK >::value();
  }
  static const char* value(const ::scara_command::CheckKinIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::CheckKinIKResponse> should match
// service_traits::DataType< ::scara_command::CheckKinIK >
template<>
struct DataType< ::scara_command::CheckKinIKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::CheckKinIK >::value();
  }
  static const char* value(const ::scara_command::CheckKinIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_CHECKKINIK_H
