// Generated by gencpp from file scara_command/ScaraKinIKResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAKINIKRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SCARAKINIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct ScaraKinIKResponse_
{
  typedef ScaraKinIKResponse_<ContainerAllocator> Type;

  ScaraKinIKResponse_()
    : success(false)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
    }
  ScaraKinIKResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef float _q1_type;
  _q1_type q1;

   typedef float _q2_type;
  _q2_type q2;

   typedef float _q3_type;
  _q3_type q3;





  typedef boost::shared_ptr< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScaraKinIKResponse_

typedef ::scara_command::ScaraKinIKResponse_<std::allocator<void> > ScaraKinIKResponse;

typedef boost::shared_ptr< ::scara_command::ScaraKinIKResponse > ScaraKinIKResponsePtr;
typedef boost::shared_ptr< ::scara_command::ScaraKinIKResponse const> ScaraKinIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::ScaraKinIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::ScaraKinIKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraKinIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.q1 == rhs.q1 &&
    lhs.q2 == rhs.q2 &&
    lhs.q3 == rhs.q3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::ScaraKinIKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraKinIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d31a4a69cd904ffc43d64713b773c91";
  }

  static const char* value(const ::scara_command::ScaraKinIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d31a4a69cd904ffULL;
  static const uint64_t static_value2 = 0xc43d64713b773c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/ScaraKinIKResponse";
  }

  static const char* value(const ::scara_command::ScaraKinIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float32 q1\n"
"float32 q2\n"
"float32 q3\n"
"\n"
;
  }

  static const char* value(const ::scara_command::ScaraKinIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScaraKinIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::ScaraKinIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::ScaraKinIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "q1: ";
    Printer<float>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<float>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<float>::stream(s, indent + "  ", v.q3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAKINIKRESPONSE_H
