// Generated by gencpp from file scara_command/ScaraKinFK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAKINFK_H
#define SCARA_COMMAND_MESSAGE_SCARAKINFK_H

#include <ros/service_traits.h>


#include <scara_command/ScaraKinFKRequest.h>
#include <scara_command/ScaraKinFKResponse.h>


namespace scara_command
{

struct ScaraKinFK
{

typedef ScaraKinFKRequest Request;
typedef ScaraKinFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScaraKinFK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::ScaraKinFK > {
  static const char* value()
  {
    return "7861a4dbb7e9452dabc20f2eff991915";
  }

  static const char* value(const ::scara_command::ScaraKinFK&) { return value(); }
};

template<>
struct DataType< ::scara_command::ScaraKinFK > {
  static const char* value()
  {
    return "scara_command/ScaraKinFK";
  }

  static const char* value(const ::scara_command::ScaraKinFK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::ScaraKinFKRequest> should match
// service_traits::MD5Sum< ::scara_command::ScaraKinFK >
template<>
struct MD5Sum< ::scara_command::ScaraKinFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraKinFK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraKinFKRequest> should match
// service_traits::DataType< ::scara_command::ScaraKinFK >
template<>
struct DataType< ::scara_command::ScaraKinFKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraKinFK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::ScaraKinFKResponse> should match
// service_traits::MD5Sum< ::scara_command::ScaraKinFK >
template<>
struct MD5Sum< ::scara_command::ScaraKinFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraKinFK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraKinFKResponse> should match
// service_traits::DataType< ::scara_command::ScaraKinFK >
template<>
struct DataType< ::scara_command::ScaraKinFKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraKinFK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAKINFK_H
