// Generated by gencpp from file scara_command/ScaraHomoMatrix.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIX_H
#define SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIX_H

#include <ros/service_traits.h>


#include <scara_command/ScaraHomoMatrixRequest.h>
#include <scara_command/ScaraHomoMatrixResponse.h>


namespace scara_command
{

struct ScaraHomoMatrix
{

typedef ScaraHomoMatrixRequest Request;
typedef ScaraHomoMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScaraHomoMatrix
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::ScaraHomoMatrix > {
  static const char* value()
  {
    return "b04a28e6794c58d88ef84b160d32201a";
  }

  static const char* value(const ::scara_command::ScaraHomoMatrix&) { return value(); }
};

template<>
struct DataType< ::scara_command::ScaraHomoMatrix > {
  static const char* value()
  {
    return "scara_command/ScaraHomoMatrix";
  }

  static const char* value(const ::scara_command::ScaraHomoMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::ScaraHomoMatrixRequest> should match
// service_traits::MD5Sum< ::scara_command::ScaraHomoMatrix >
template<>
struct MD5Sum< ::scara_command::ScaraHomoMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraHomoMatrix >::value();
  }
  static const char* value(const ::scara_command::ScaraHomoMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraHomoMatrixRequest> should match
// service_traits::DataType< ::scara_command::ScaraHomoMatrix >
template<>
struct DataType< ::scara_command::ScaraHomoMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraHomoMatrix >::value();
  }
  static const char* value(const ::scara_command::ScaraHomoMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::ScaraHomoMatrixResponse> should match
// service_traits::MD5Sum< ::scara_command::ScaraHomoMatrix >
template<>
struct MD5Sum< ::scara_command::ScaraHomoMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraHomoMatrix >::value();
  }
  static const char* value(const ::scara_command::ScaraHomoMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraHomoMatrixResponse> should match
// service_traits::DataType< ::scara_command::ScaraHomoMatrix >
template<>
struct DataType< ::scara_command::ScaraHomoMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraHomoMatrix >::value();
  }
  static const char* value(const ::scara_command::ScaraHomoMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIX_H
