// Generated by gencpp from file scara_command/ScaraHomoMatrixResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIXRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace scara_command
{
template <class ContainerAllocator>
struct ScaraHomoMatrixResponse_
{
  typedef ScaraHomoMatrixResponse_<ContainerAllocator> Type;

  ScaraHomoMatrixResponse_()
    : A1()
    , A2()
    , A3()  {
    }
  ScaraHomoMatrixResponse_(const ContainerAllocator& _alloc)
    : A1(_alloc)
    , A2(_alloc)
    , A3(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _A1_type;
  _A1_type A1;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _A2_type;
  _A2_type A2;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _A3_type;
  _A3_type A3;





  typedef boost::shared_ptr< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScaraHomoMatrixResponse_

typedef ::scara_command::ScaraHomoMatrixResponse_<std::allocator<void> > ScaraHomoMatrixResponse;

typedef boost::shared_ptr< ::scara_command::ScaraHomoMatrixResponse > ScaraHomoMatrixResponsePtr;
typedef boost::shared_ptr< ::scara_command::ScaraHomoMatrixResponse const> ScaraHomoMatrixResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator2> & rhs)
{
  return lhs.A1 == rhs.A1 &&
    lhs.A2 == rhs.A2 &&
    lhs.A3 == rhs.A3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d3246727dfc9f450b1b9de106536d12";
  }

  static const char* value(const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d3246727dfc9f45ULL;
  static const uint64_t static_value2 = 0x0b1b9de106536d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/ScaraHomoMatrixResponse";
  }

  static const char* value(const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray A1\n"
"std_msgs/Float32MultiArray A2\n"
"std_msgs/Float32MultiArray A3\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A1);
      stream.next(m.A2);
      stream.next(m.A3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScaraHomoMatrixResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::ScaraHomoMatrixResponse_<ContainerAllocator>& v)
  {
    s << indent << "A1: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.A1);
    s << indent << "A2: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.A2);
    s << indent << "A3: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.A3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAHOMOMATRIXRESPONSE_H
