// Generated by gencpp from file scara_command/ScaraVelFKResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAVELFKRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SCARAVELFKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct ScaraVelFKResponse_
{
  typedef ScaraVelFKResponse_<ContainerAllocator> Type;

  ScaraVelFKResponse_()
    : Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Wx(0.0)
    , Wy(0.0)
    , Wz(0.0)  {
    }
  ScaraVelFKResponse_(const ContainerAllocator& _alloc)
    : Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Wx(0.0)
    , Wy(0.0)
    , Wz(0.0)  {
  (void)_alloc;
    }



   typedef float _Vx_type;
  _Vx_type Vx;

   typedef float _Vy_type;
  _Vy_type Vy;

   typedef float _Vz_type;
  _Vz_type Vz;

   typedef float _Wx_type;
  _Wx_type Wx;

   typedef float _Wy_type;
  _Wy_type Wy;

   typedef float _Wz_type;
  _Wz_type Wz;





  typedef boost::shared_ptr< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScaraVelFKResponse_

typedef ::scara_command::ScaraVelFKResponse_<std::allocator<void> > ScaraVelFKResponse;

typedef boost::shared_ptr< ::scara_command::ScaraVelFKResponse > ScaraVelFKResponsePtr;
typedef boost::shared_ptr< ::scara_command::ScaraVelFKResponse const> ScaraVelFKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::ScaraVelFKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::ScaraVelFKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelFKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Vx == rhs.Vx &&
    lhs.Vy == rhs.Vy &&
    lhs.Vz == rhs.Vz &&
    lhs.Wx == rhs.Wx &&
    lhs.Wy == rhs.Wy &&
    lhs.Wz == rhs.Wz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::ScaraVelFKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelFKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ab779f0d7049dba7eeb7834b2b71119";
  }

  static const char* value(const ::scara_command::ScaraVelFKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ab779f0d7049dbaULL;
  static const uint64_t static_value2 = 0x7eeb7834b2b71119ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/ScaraVelFKResponse";
  }

  static const char* value(const ::scara_command::ScaraVelFKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Vx\n"
"float32 Vy\n"
"float32 Vz\n"
"float32 Wx\n"
"float32 Wy\n"
"float32 Wz\n"
"\n"
;
  }

  static const char* value(const ::scara_command::ScaraVelFKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Vx);
      stream.next(m.Vy);
      stream.next(m.Vz);
      stream.next(m.Wx);
      stream.next(m.Wy);
      stream.next(m.Wz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScaraVelFKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::ScaraVelFKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::ScaraVelFKResponse_<ContainerAllocator>& v)
  {
    s << indent << "Vx: ";
    Printer<float>::stream(s, indent + "  ", v.Vx);
    s << indent << "Vy: ";
    Printer<float>::stream(s, indent + "  ", v.Vy);
    s << indent << "Vz: ";
    Printer<float>::stream(s, indent + "  ", v.Vz);
    s << indent << "Wx: ";
    Printer<float>::stream(s, indent + "  ", v.Wx);
    s << indent << "Wy: ";
    Printer<float>::stream(s, indent + "  ", v.Wy);
    s << indent << "Wz: ";
    Printer<float>::stream(s, indent + "  ", v.Wz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAVELFKRESPONSE_H
