// Generated by gencpp from file scara_command/ScaraVelIK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAVELIK_H
#define SCARA_COMMAND_MESSAGE_SCARAVELIK_H

#include <ros/service_traits.h>


#include <scara_command/ScaraVelIKRequest.h>
#include <scara_command/ScaraVelIKResponse.h>


namespace scara_command
{

struct ScaraVelIK
{

typedef ScaraVelIKRequest Request;
typedef ScaraVelIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScaraVelIK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::ScaraVelIK > {
  static const char* value()
  {
    return "273c8e596b5ffa32d13cf21237d3aaf2";
  }

  static const char* value(const ::scara_command::ScaraVelIK&) { return value(); }
};

template<>
struct DataType< ::scara_command::ScaraVelIK > {
  static const char* value()
  {
    return "scara_command/ScaraVelIK";
  }

  static const char* value(const ::scara_command::ScaraVelIK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::ScaraVelIKRequest> should match
// service_traits::MD5Sum< ::scara_command::ScaraVelIK >
template<>
struct MD5Sum< ::scara_command::ScaraVelIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraVelIK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraVelIKRequest> should match
// service_traits::DataType< ::scara_command::ScaraVelIK >
template<>
struct DataType< ::scara_command::ScaraVelIKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraVelIK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::ScaraVelIKResponse> should match
// service_traits::MD5Sum< ::scara_command::ScaraVelIK >
template<>
struct MD5Sum< ::scara_command::ScaraVelIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraVelIK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraVelIKResponse> should match
// service_traits::DataType< ::scara_command::ScaraVelIK >
template<>
struct DataType< ::scara_command::ScaraVelIKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraVelIK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAVELIK_H
