// Generated by gencpp from file scara_command/ScaraVelFK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAVELFK_H
#define SCARA_COMMAND_MESSAGE_SCARAVELFK_H

#include <ros/service_traits.h>


#include <scara_command/ScaraVelFKRequest.h>
#include <scara_command/ScaraVelFKResponse.h>


namespace scara_command
{

struct ScaraVelFK
{

typedef ScaraVelFKRequest Request;
typedef ScaraVelFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScaraVelFK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::ScaraVelFK > {
  static const char* value()
  {
    return "d154cd82f0b9fb9f1cf33ba88636c898";
  }

  static const char* value(const ::scara_command::ScaraVelFK&) { return value(); }
};

template<>
struct DataType< ::scara_command::ScaraVelFK > {
  static const char* value()
  {
    return "scara_command/ScaraVelFK";
  }

  static const char* value(const ::scara_command::ScaraVelFK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::ScaraVelFKRequest> should match
// service_traits::MD5Sum< ::scara_command::ScaraVelFK >
template<>
struct MD5Sum< ::scara_command::ScaraVelFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraVelFK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraVelFKRequest> should match
// service_traits::DataType< ::scara_command::ScaraVelFK >
template<>
struct DataType< ::scara_command::ScaraVelFKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraVelFK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::ScaraVelFKResponse> should match
// service_traits::MD5Sum< ::scara_command::ScaraVelFK >
template<>
struct MD5Sum< ::scara_command::ScaraVelFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraVelFK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraVelFKResponse> should match
// service_traits::DataType< ::scara_command::ScaraVelFK >
template<>
struct DataType< ::scara_command::ScaraVelFKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraVelFK >::value();
  }
  static const char* value(const ::scara_command::ScaraVelFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAVELFK_H
