// Generated by gencpp from file scara_command/ScaraKinIK.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAKINIK_H
#define SCARA_COMMAND_MESSAGE_SCARAKINIK_H

#include <ros/service_traits.h>


#include <scara_command/ScaraKinIKRequest.h>
#include <scara_command/ScaraKinIKResponse.h>


namespace scara_command
{

struct ScaraKinIK
{

typedef ScaraKinIKRequest Request;
typedef ScaraKinIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScaraKinIK
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::ScaraKinIK > {
  static const char* value()
  {
    return "90f36ce76dbe958bc51489fea1b8cf59";
  }

  static const char* value(const ::scara_command::ScaraKinIK&) { return value(); }
};

template<>
struct DataType< ::scara_command::ScaraKinIK > {
  static const char* value()
  {
    return "scara_command/ScaraKinIK";
  }

  static const char* value(const ::scara_command::ScaraKinIK&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::ScaraKinIKRequest> should match
// service_traits::MD5Sum< ::scara_command::ScaraKinIK >
template<>
struct MD5Sum< ::scara_command::ScaraKinIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraKinIK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraKinIKRequest> should match
// service_traits::DataType< ::scara_command::ScaraKinIK >
template<>
struct DataType< ::scara_command::ScaraKinIKRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraKinIK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::ScaraKinIKResponse> should match
// service_traits::MD5Sum< ::scara_command::ScaraKinIK >
template<>
struct MD5Sum< ::scara_command::ScaraKinIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::ScaraKinIK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::ScaraKinIKResponse> should match
// service_traits::DataType< ::scara_command::ScaraKinIK >
template<>
struct DataType< ::scara_command::ScaraKinIKResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::ScaraKinIK >::value();
  }
  static const char* value(const ::scara_command::ScaraKinIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAKINIK_H
