// Generated by gencpp from file scara_command/ScaraVelIKRequest.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAVELIKREQUEST_H
#define SCARA_COMMAND_MESSAGE_SCARAVELIKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct ScaraVelIKRequest_
{
  typedef ScaraVelIKRequest_<ContainerAllocator> Type;

  ScaraVelIKRequest_()
    : q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Wx(0.0)
    , Wy(0.0)
    , Wz(0.0)  {
    }
  ScaraVelIKRequest_(const ContainerAllocator& _alloc)
    : q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Wx(0.0)
    , Wy(0.0)
    , Wz(0.0)  {
  (void)_alloc;
    }



   typedef float _q1_type;
  _q1_type q1;

   typedef float _q2_type;
  _q2_type q2;

   typedef float _q3_type;
  _q3_type q3;

   typedef float _Vx_type;
  _Vx_type Vx;

   typedef float _Vy_type;
  _Vy_type Vy;

   typedef float _Vz_type;
  _Vz_type Vz;

   typedef float _Wx_type;
  _Wx_type Wx;

   typedef float _Wy_type;
  _Wy_type Wy;

   typedef float _Wz_type;
  _Wz_type Wz;





  typedef boost::shared_ptr< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ScaraVelIKRequest_

typedef ::scara_command::ScaraVelIKRequest_<std::allocator<void> > ScaraVelIKRequest;

typedef boost::shared_ptr< ::scara_command::ScaraVelIKRequest > ScaraVelIKRequestPtr;
typedef boost::shared_ptr< ::scara_command::ScaraVelIKRequest const> ScaraVelIKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::ScaraVelIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::ScaraVelIKRequest_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelIKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q1 == rhs.q1 &&
    lhs.q2 == rhs.q2 &&
    lhs.q3 == rhs.q3 &&
    lhs.Vx == rhs.Vx &&
    lhs.Vy == rhs.Vy &&
    lhs.Vz == rhs.Vz &&
    lhs.Wx == rhs.Wx &&
    lhs.Wy == rhs.Wy &&
    lhs.Wz == rhs.Wz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::ScaraVelIKRequest_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelIKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a7f08bc2df9b68690007784109f3edc";
  }

  static const char* value(const ::scara_command::ScaraVelIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a7f08bc2df9b686ULL;
  static const uint64_t static_value2 = 0x90007784109f3edcULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/ScaraVelIKRequest";
  }

  static const char* value(const ::scara_command::ScaraVelIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 q1\n"
"float32 q2\n"
"float32 q3\n"
"float32 Vx\n"
"float32 Vy\n"
"float32 Vz\n"
"float32 Wx\n"
"float32 Wy\n"
"float32 Wz\n"
;
  }

  static const char* value(const ::scara_command::ScaraVelIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
      stream.next(m.Vx);
      stream.next(m.Vy);
      stream.next(m.Vz);
      stream.next(m.Wx);
      stream.next(m.Wy);
      stream.next(m.Wz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScaraVelIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::ScaraVelIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::ScaraVelIKRequest_<ContainerAllocator>& v)
  {
    s << indent << "q1: ";
    Printer<float>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<float>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<float>::stream(s, indent + "  ", v.q3);
    s << indent << "Vx: ";
    Printer<float>::stream(s, indent + "  ", v.Vx);
    s << indent << "Vy: ";
    Printer<float>::stream(s, indent + "  ", v.Vy);
    s << indent << "Vz: ";
    Printer<float>::stream(s, indent + "  ", v.Vz);
    s << indent << "Wx: ";
    Printer<float>::stream(s, indent + "  ", v.Wx);
    s << indent << "Wy: ";
    Printer<float>::stream(s, indent + "  ", v.Wy);
    s << indent << "Wz: ";
    Printer<float>::stream(s, indent + "  ", v.Wz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAVELIKREQUEST_H
