// Generated by gencpp from file scara_command/ScaraVelIKResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SCARAVELIKRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SCARAVELIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct ScaraVelIKResponse_
{
  typedef ScaraVelIKResponse_<ContainerAllocator> Type;

  ScaraVelIKResponse_()
    : success(false)
    , q1_dot(0.0)
    , q2_dot(0.0)
    , q3_dot(0.0)  {
    }
  ScaraVelIKResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , q1_dot(0.0)
    , q2_dot(0.0)
    , q3_dot(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef float _q1_dot_type;
  _q1_dot_type q1_dot;

   typedef float _q2_dot_type;
  _q2_dot_type q2_dot;

   typedef float _q3_dot_type;
  _q3_dot_type q3_dot;





  typedef boost::shared_ptr< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScaraVelIKResponse_

typedef ::scara_command::ScaraVelIKResponse_<std::allocator<void> > ScaraVelIKResponse;

typedef boost::shared_ptr< ::scara_command::ScaraVelIKResponse > ScaraVelIKResponsePtr;
typedef boost::shared_ptr< ::scara_command::ScaraVelIKResponse const> ScaraVelIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::ScaraVelIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::ScaraVelIKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.q1_dot == rhs.q1_dot &&
    lhs.q2_dot == rhs.q2_dot &&
    lhs.q3_dot == rhs.q3_dot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::ScaraVelIKResponse_<ContainerAllocator1> & lhs, const ::scara_command::ScaraVelIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a1167ccfb083ccdaf6e453d6a0272a3";
  }

  static const char* value(const ::scara_command::ScaraVelIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a1167ccfb083ccdULL;
  static const uint64_t static_value2 = 0xaf6e453d6a0272a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/ScaraVelIKResponse";
  }

  static const char* value(const ::scara_command::ScaraVelIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float32 q1_dot\n"
"float32 q2_dot\n"
"float32 q3_dot\n"
"\n"
;
  }

  static const char* value(const ::scara_command::ScaraVelIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.q1_dot);
      stream.next(m.q2_dot);
      stream.next(m.q3_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScaraVelIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::ScaraVelIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::ScaraVelIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "q1_dot: ";
    Printer<float>::stream(s, indent + "  ", v.q1_dot);
    s << indent << "q2_dot: ";
    Printer<float>::stream(s, indent + "  ", v.q2_dot);
    s << indent << "q3_dot: ";
    Printer<float>::stream(s, indent + "  ", v.q3_dot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SCARAVELIKRESPONSE_H
