// Generated by gencpp from file scara_command/SetCartesianVelResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SETCARTESIANVELRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SETCARTESIANVELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct SetCartesianVelResponse_
{
  typedef SetCartesianVelResponse_<ContainerAllocator> Type;

  SetCartesianVelResponse_()
    : success(false)  {
    }
  SetCartesianVelResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCartesianVelResponse_

typedef ::scara_command::SetCartesianVelResponse_<std::allocator<void> > SetCartesianVelResponse;

typedef boost::shared_ptr< ::scara_command::SetCartesianVelResponse > SetCartesianVelResponsePtr;
typedef boost::shared_ptr< ::scara_command::SetCartesianVelResponse const> SetCartesianVelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::SetCartesianVelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::SetCartesianVelResponse_<ContainerAllocator1> & lhs, const ::scara_command::SetCartesianVelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::SetCartesianVelResponse_<ContainerAllocator1> & lhs, const ::scara_command::SetCartesianVelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::scara_command::SetCartesianVelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/SetCartesianVelResponse";
  }

  static const char* value(const ::scara_command::SetCartesianVelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::scara_command::SetCartesianVelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCartesianVelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::SetCartesianVelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::SetCartesianVelResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SETCARTESIANVELRESPONSE_H
