// Generated by gencpp from file scara_command/SetCartesianPosRequest.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SETCARTESIANPOSREQUEST_H
#define SCARA_COMMAND_MESSAGE_SETCARTESIANPOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct SetCartesianPosRequest_
{
  typedef SetCartesianPosRequest_<ContainerAllocator> Type;

  SetCartesianPosRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  SetCartesianPosRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCartesianPosRequest_

typedef ::scara_command::SetCartesianPosRequest_<std::allocator<void> > SetCartesianPosRequest;

typedef boost::shared_ptr< ::scara_command::SetCartesianPosRequest > SetCartesianPosRequestPtr;
typedef boost::shared_ptr< ::scara_command::SetCartesianPosRequest const> SetCartesianPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::SetCartesianPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::SetCartesianPosRequest_<ContainerAllocator1> & lhs, const ::scara_command::SetCartesianPosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::SetCartesianPosRequest_<ContainerAllocator1> & lhs, const ::scara_command::SetCartesianPosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::scara_command::SetCartesianPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/SetCartesianPosRequest";
  }

  static const char* value(const ::scara_command::SetCartesianPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::scara_command::SetCartesianPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCartesianPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::SetCartesianPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::SetCartesianPosRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SETCARTESIANPOSREQUEST_H
