// Generated by gencpp from file scara_command/SetCartesianVel.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SETCARTESIANVEL_H
#define SCARA_COMMAND_MESSAGE_SETCARTESIANVEL_H

#include <ros/service_traits.h>


#include <scara_command/SetCartesianVelRequest.h>
#include <scara_command/SetCartesianVelResponse.h>


namespace scara_command
{

struct SetCartesianVel
{

typedef SetCartesianVelRequest Request;
typedef SetCartesianVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCartesianVel
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::SetCartesianVel > {
  static const char* value()
  {
    return "283707b7ad403b8c31a22ddc99890608";
  }

  static const char* value(const ::scara_command::SetCartesianVel&) { return value(); }
};

template<>
struct DataType< ::scara_command::SetCartesianVel > {
  static const char* value()
  {
    return "scara_command/SetCartesianVel";
  }

  static const char* value(const ::scara_command::SetCartesianVel&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::SetCartesianVelRequest> should match
// service_traits::MD5Sum< ::scara_command::SetCartesianVel >
template<>
struct MD5Sum< ::scara_command::SetCartesianVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetCartesianVel >::value();
  }
  static const char* value(const ::scara_command::SetCartesianVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetCartesianVelRequest> should match
// service_traits::DataType< ::scara_command::SetCartesianVel >
template<>
struct DataType< ::scara_command::SetCartesianVelRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetCartesianVel >::value();
  }
  static const char* value(const ::scara_command::SetCartesianVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::SetCartesianVelResponse> should match
// service_traits::MD5Sum< ::scara_command::SetCartesianVel >
template<>
struct MD5Sum< ::scara_command::SetCartesianVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetCartesianVel >::value();
  }
  static const char* value(const ::scara_command::SetCartesianVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetCartesianVelResponse> should match
// service_traits::DataType< ::scara_command::SetCartesianVel >
template<>
struct DataType< ::scara_command::SetCartesianVelResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetCartesianVel >::value();
  }
  static const char* value(const ::scara_command::SetCartesianVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SETCARTESIANVEL_H
