// Generated by gencpp from file scara_command/SetCartesianPos.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SETCARTESIANPOS_H
#define SCARA_COMMAND_MESSAGE_SETCARTESIANPOS_H

#include <ros/service_traits.h>


#include <scara_command/SetCartesianPosRequest.h>
#include <scara_command/SetCartesianPosResponse.h>


namespace scara_command
{

struct SetCartesianPos
{

typedef SetCartesianPosRequest Request;
typedef SetCartesianPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCartesianPos
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::SetCartesianPos > {
  static const char* value()
  {
    return "58d59f258ca9f2d2ba375d9428a7f1de";
  }

  static const char* value(const ::scara_command::SetCartesianPos&) { return value(); }
};

template<>
struct DataType< ::scara_command::SetCartesianPos > {
  static const char* value()
  {
    return "scara_command/SetCartesianPos";
  }

  static const char* value(const ::scara_command::SetCartesianPos&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::SetCartesianPosRequest> should match
// service_traits::MD5Sum< ::scara_command::SetCartesianPos >
template<>
struct MD5Sum< ::scara_command::SetCartesianPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetCartesianPos >::value();
  }
  static const char* value(const ::scara_command::SetCartesianPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetCartesianPosRequest> should match
// service_traits::DataType< ::scara_command::SetCartesianPos >
template<>
struct DataType< ::scara_command::SetCartesianPosRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetCartesianPos >::value();
  }
  static const char* value(const ::scara_command::SetCartesianPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::SetCartesianPosResponse> should match
// service_traits::MD5Sum< ::scara_command::SetCartesianPos >
template<>
struct MD5Sum< ::scara_command::SetCartesianPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetCartesianPos >::value();
  }
  static const char* value(const ::scara_command::SetCartesianPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetCartesianPosResponse> should match
// service_traits::DataType< ::scara_command::SetCartesianPos >
template<>
struct DataType< ::scara_command::SetCartesianPosResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetCartesianPos >::value();
  }
  static const char* value(const ::scara_command::SetCartesianPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SETCARTESIANPOS_H
