// Generated by gencpp from file scara_command/SetJointRef.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SETJOINTREF_H
#define SCARA_COMMAND_MESSAGE_SETJOINTREF_H

#include <ros/service_traits.h>


#include <scara_command/SetJointRefRequest.h>
#include <scara_command/SetJointRefResponse.h>


namespace scara_command
{

struct SetJointRef
{

typedef SetJointRefRequest Request;
typedef SetJointRefResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointRef
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::SetJointRef > {
  static const char* value()
  {
    return "6f194d3e831f68db4bba0c86e04a9975";
  }

  static const char* value(const ::scara_command::SetJointRef&) { return value(); }
};

template<>
struct DataType< ::scara_command::SetJointRef > {
  static const char* value()
  {
    return "scara_command/SetJointRef";
  }

  static const char* value(const ::scara_command::SetJointRef&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::SetJointRefRequest> should match
// service_traits::MD5Sum< ::scara_command::SetJointRef >
template<>
struct MD5Sum< ::scara_command::SetJointRefRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetJointRef >::value();
  }
  static const char* value(const ::scara_command::SetJointRefRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetJointRefRequest> should match
// service_traits::DataType< ::scara_command::SetJointRef >
template<>
struct DataType< ::scara_command::SetJointRefRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetJointRef >::value();
  }
  static const char* value(const ::scara_command::SetJointRefRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::SetJointRefResponse> should match
// service_traits::MD5Sum< ::scara_command::SetJointRef >
template<>
struct MD5Sum< ::scara_command::SetJointRefResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SetJointRef >::value();
  }
  static const char* value(const ::scara_command::SetJointRefResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SetJointRefResponse> should match
// service_traits::DataType< ::scara_command::SetJointRef >
template<>
struct DataType< ::scara_command::SetJointRefResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::SetJointRef >::value();
  }
  static const char* value(const ::scara_command::SetJointRefResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SETJOINTREF_H
