// Generated by gencpp from file scara_command/SwitchControlResponse.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SWITCHCONTROLRESPONSE_H
#define SCARA_COMMAND_MESSAGE_SWITCHCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_command
{
template <class ContainerAllocator>
struct SwitchControlResponse_
{
  typedef SwitchControlResponse_<ContainerAllocator> Type;

  SwitchControlResponse_()
    : success(false)  {
    }
  SwitchControlResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::scara_command::SwitchControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_command::SwitchControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchControlResponse_

typedef ::scara_command::SwitchControlResponse_<std::allocator<void> > SwitchControlResponse;

typedef boost::shared_ptr< ::scara_command::SwitchControlResponse > SwitchControlResponsePtr;
typedef boost::shared_ptr< ::scara_command::SwitchControlResponse const> SwitchControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_command::SwitchControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_command::SwitchControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_command::SwitchControlResponse_<ContainerAllocator1> & lhs, const ::scara_command::SwitchControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_command::SwitchControlResponse_<ContainerAllocator1> & lhs, const ::scara_command::SwitchControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_command::SwitchControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_command::SwitchControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_command::SwitchControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::scara_command::SwitchControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_command/SwitchControlResponse";
  }

  static const char* value(const ::scara_command::SwitchControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::scara_command::SwitchControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_command::SwitchControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_command::SwitchControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SWITCHCONTROLRESPONSE_H
