// Generated by gencpp from file scara_command/SwitchControl.msg
// DO NOT EDIT!


#ifndef SCARA_COMMAND_MESSAGE_SWITCHCONTROL_H
#define SCARA_COMMAND_MESSAGE_SWITCHCONTROL_H

#include <ros/service_traits.h>


#include <scara_command/SwitchControlRequest.h>
#include <scara_command/SwitchControlResponse.h>


namespace scara_command
{

struct SwitchControl
{

typedef SwitchControlRequest Request;
typedef SwitchControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchControl
} // namespace scara_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_command::SwitchControl > {
  static const char* value()
  {
    return "031d24522d462b2314fd1b6270670dd2";
  }

  static const char* value(const ::scara_command::SwitchControl&) { return value(); }
};

template<>
struct DataType< ::scara_command::SwitchControl > {
  static const char* value()
  {
    return "scara_command/SwitchControl";
  }

  static const char* value(const ::scara_command::SwitchControl&) { return value(); }
};


// service_traits::MD5Sum< ::scara_command::SwitchControlRequest> should match
// service_traits::MD5Sum< ::scara_command::SwitchControl >
template<>
struct MD5Sum< ::scara_command::SwitchControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SwitchControl >::value();
  }
  static const char* value(const ::scara_command::SwitchControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SwitchControlRequest> should match
// service_traits::DataType< ::scara_command::SwitchControl >
template<>
struct DataType< ::scara_command::SwitchControlRequest>
{
  static const char* value()
  {
    return DataType< ::scara_command::SwitchControl >::value();
  }
  static const char* value(const ::scara_command::SwitchControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_command::SwitchControlResponse> should match
// service_traits::MD5Sum< ::scara_command::SwitchControl >
template<>
struct MD5Sum< ::scara_command::SwitchControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_command::SwitchControl >::value();
  }
  static const char* value(const ::scara_command::SwitchControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_command::SwitchControlResponse> should match
// service_traits::DataType< ::scara_command::SwitchControl >
template<>
struct DataType< ::scara_command::SwitchControlResponse>
{
  static const char* value()
  {
    return DataType< ::scara_command::SwitchControl >::value();
  }
  static const char* value(const ::scara_command::SwitchControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_COMMAND_MESSAGE_SWITCHCONTROL_H
