vsbot :
# Deep learning parameters
  deeplearning:
    # weights_path: '/home/jc-merlab/Pictures/Data/trained_models/keypointsrcnn_weights_ld_b1_e30.pth'
    weights_path: '/home/jc-merlab/Pictures/Data/trained_models/keypointsrcnn_planning_b1_e100_v4.pth'

# Jacobian Estimation Parameters ------------------------------------
  estimation:
    epsilon: 1.0e-5 # update threshold or convergence condition
    gamma:  10.0 # learning rate
    gamma2: 30.0 # learning rate during servoing
    gamma3: 50.0
    window: 50 # window size
    amplitude: 0.1 # amplitude for initial sin velocities
    rate: 10 # initialization loop rate

  control:
    saturation: 20      
    gain_sm: -3
    thresh1: 20 # visual servoing convergence threshold
    thresh2: 5
    lam: -0.3 # for 2 joints
    p_lam: 0.5
    alpha_gamma: 0.2
    alpha_gains: 0.001
    reg_lambda: 0.01
    # jacobian: [19, 47, -79,  7, 89, -13, 71, -59, -23, 61, 41, -67,  -3,  2, -11, 29, -43, -31, 73, 17, -5, 83, 37, 53]
    jacobian: [19, 17, -47, 31, -89, 41, 151, -97, -73, 163, 139, 149, -173, 103, 83, -53, 79, 7, -29, 67, 113, -109, 2, 37, 107, -59, 13, 127, 71, 137] #, 101, 23, 157, -131, 167, 3]
    # jacobian: [19, 47, -79,  7, 89, -13, 71, -59, -23, 61, 41, -67]  #,-3,  2, -11, 29, -43, -31, 73, 17, -5, 83, 37, 53]
    # jacobian: [19, 47, -79,  7, 89, -13, 71, -59, -23, 61, 41, -67,  -3,  2, -11, 29, -43, -31]
    gains1: [-2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0] # for intermediate configs
    # gains2: [-1.5, -1.5, -1.5, -1.5, -3.0, -3.0, -5.0, -5.0] # for last config
    gains2: [-4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0]

# Shape Servoing Parameters -------------------------------------------
  
  shape_control:     
    no_of_features: 10
    no_of_actuators: 3
    num_of_segments: 2