header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
  - 'panda_joint1'
  - 'panda_joint2'
  - 'panda_joint3'
  - 'panda_joint4'
  - 'panda_joint5'
  - 'panda_joint6'
  - 'panda_joint7'
points:
  - positions: [0.007195404887023141, -0.9331, -0.008532170082858044, -1.33819, 0.0010219530727038648, 2.2474, 0.8118303423692146]
    velocities: [0, 0, 0, 0, 0, 0, 0]
    accelerations: [0, 0, 0, 0, 0, 0, 0]
    effort: [0, 0, 0, 0, 0, 0, 0]
    time_from_start:
      secs: 30
      nsecs: 0